baseurl      = ""
title        = "Thomas Hammer"
languageCode = "fr-fr"
theme        = "hello-friend-ng"
relativeURLs = false
uglyURLs     = false

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  
  # Set the section to show in list view
  mainSections = ["blog"]

  # Subtitle for home
  homeSubtitle = "Bricoleur du web"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "Simplement une landing page pour le bricoleur du web"
  keywords = "homepage"
  images = [""]

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/thomas-hammer-2a36283b/"

[[params.social]]
name = "github"
url = "https://github.com/hammer-t"

[[params.social]]
name = "email"
url = "mailto:thomas@bricoleurduweb.fr"

[[params.social]]
name = "CV"
url = "cv.pdf"

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[menu]
  [[menu.main]]
    identifier = "home"
    name       = "Accueil"
    url        = "/"
    weight     = 10

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/blog"
    weight     = 20

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML"]
